CREATE TABLE CIUDAD (
    ID_Ciudad INT PRIMARY KEY NOT NULL UNIQUE,
    Nombre_Ciudad VARCHAR(255) NOT NULL
);
CREATE TABLE DIRECCION (
    ID_Direccion INT PRIMARY KEY NOT NULL UNIQUE,
    ID_Ciudad INT NOT NULL,
    Calle VARCHAR(255) NOT NULL,
    Numeracion VARCHAR(10) NOT NULL,
    Codigo_Postal NUMERIC(10) NOT NULL,
    FOREIGN KEY (ID_Ciudad) REFERENCES CIUDAD(ID_Ciudad)
);
CREATE TABLE PROVEEDORES (
    ID_Proveedor INT PRIMARY KEY NOT NULL UNIQUE,
    Nombre VARCHAR(255) NOT NULL,
    DNI VARCHAR(20) NOT NULL,
    Teléfono VARCHAR(20) NOT NULL,
    ID_Direccion INT NOT NULL,
    FOREIGN KEY (ID_Direccion) REFERENCES DIRECCION(ID_Direccion)
);
CREATE TABLE EMPLEADOS (
    ID_Empleado INT PRIMARY KEY NOT NULL UNIQUE,
    ID_Direccion INT NOT NULL,
    Nombre VARCHAR(255) NOT NULL,
    DNI VARCHAR(255) NOT NULL,
    Telefono NUMERIC(20,0) NOT NULL,
    FOREIGN KEY (ID_Direccion) REFERENCES DIRECCION(ID_Direccion)
);
CREATE TABLE CLIENTES (
    ID_Cliente INT PRIMARY KEY NOT NULL UNIQUE,
    ID_Direccion INT NOT NULL,
    Nombre VARCHAR(255) NOT NULL,
    DNI VARCHAR(255) NOT NULL,
    Telefono NUMERIC(20,0) NOT NULL,
    FOREIGN KEY (ID_Direccion) REFERENCES DIRECCION(ID_Direccion)
);
CREATE TABLE PRODUCTOS (
    ID_Producto INT PRIMARY KEY NOT NULL UNIQUE,
    Nombre VARCHAR(255) NOT NULL,
    Precio DECIMAL(10,2) NOT NULL,
    Cantidad_en_Stock INT NOT NULL,
    Unidad_de_Medida VARCHAR(50) NOT NULL
);
CREATE TABLE PRODUCTO_PROVEEDOR (
    ID_ProductoProveedor INT PRIMARY KEY NOT NULL UNIQUE,
    ID_Producto INT NOT NULL,
    ID_Proveedor INT NOT NULL,
    Precio_de_Suministro DECIMAL(10,2) NOT NULL,
    Fecha_de_Suministro DATE NOT NULL,
    Cantidad INT NOT NULL,
    Metodo_Pago VARCHAR(255),
    Metodo_Envio VARCHAR(255),
    FOREIGN KEY (ID_Producto) REFERENCES PRODUCTOS(ID_Producto),
    FOREIGN KEY (ID_Proveedor) REFERENCES PROVEEDORES(ID_Proveedor)
);
CREATE TABLE PEDIDOS (
    ID_Pedido INT PRIMARY KEY NOT NULL UNIQUE,
    ID_Cliente INT NOT NULL,
    Fecha DATE NOT NULL,
    Otros_Detalles TEXT,
    FOREIGN KEY (ID_Cliente) REFERENCES CLIENTES(ID_Cliente)
);
CREATE TABLE DETALLES_DE_PEDIDO (
    ID_Detalle INT PRIMARY KEY NOT NULL UNIQUE,
    ID_Pedido INT NOT NULL,
    ID_Producto INT NOT NULL,
    ID_Empleado INT NOT NULL,
    Cantidad INT NOT NULL,
    FOREIGN KEY (ID_Pedido) REFERENCES PEDIDOS(ID_Pedido),
    FOREIGN KEY (ID_Producto) REFERENCES PRODUCTOS(ID_Producto),
    FOREIGN KEY (ID_Empleado) REFERENCES EMPLEADOS(ID_Empleado)
);
CREATE TABLE PROMOCIONES (
    ID_Promocion INT PRIMARY KEY NOT NULL UNIQUE,
    Descripcion VARCHAR(255)
);
CREATE TABLE DETALLES_DE_PROMOCION (
    ID_Detalle_Promocion INT PRIMARY KEY NOT NULL UNIQUE,
    ID_Promocion INT NOT NULL,
    ID_Producto INT NOT NULL,
    FOREIGN KEY (ID_Promocion) REFERENCES PROMOCIONES(ID_Promocion),
    FOREIGN KEY (ID_Producto) REFERENCES PRODUCTOS(ID_Producto)
);